name: CI/CD to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t my-spring-app .

    - name: Save Docker image as tar
      run: docker save my-spring-app | gzip > app.tar.gz

    - name: Copy Docker image to EC2 via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "app.tar.gz"
        target: "/home/ec2-user"

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker load < app.tar.gz
          docker stop my-app || true
          docker rm my-app || true
          docker run -d -p 8085:8080 --name my-app my-spring-app
